file_format: "1"
id: totem
name: TOTEM
type: shield
url: https://github.com/GEIGEIGEIST/TOTEM
requires: [pro_micro]
features:
  - keys
  - studio
siblings:
  - totem_left
  - totem_right
  - totem_dongle
