include:
  - board: nice_nano_v2
    shield: totem_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: totem-left
  - board: nice_nano_v2
    shield: totem_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: totem-right
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_screen
    cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000 -DCONFIG_ZMK_STUDIO=y
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: totem-dongle-yads
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: totem-settings-reset
